import { Property, Agent, Raffle, Testimonial, VirtualExpo } from "@/types";

export const ALL_PROPERTIES: Property[] = [
  {
    id: "1",
    title: "Luxury Beachfront Villa in Punta Cana",
    price: 850000,
    location: "Punta Cana, La Altagracia",
    city: "Punta Cana",
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    ],
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    type: "villa",
    status: "for-sale",
    featured: true,
    agentId: "1",
    description:
      "Stunning beachfront villa with panoramic ocean views. This exceptional property features open-concept living areas, a gourmet kitchen, and a private pool steps from the Caribbean Sea. Perfect for luxury living or an upscale vacation rental investment.",
    amenities: ["Pool", "Beach Access", "Gym", "Security", "Air Conditioning", "Parking"],
    createdAt: "2025-01-01",
  },
  {
    id: "2",
    title: "Modern Penthouse in Santo Domingo",
    price: 425000,
    location: "Piantini, Santo Domingo",
    city: "Santo Domingo",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
    ],
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    type: "penthouse",
    status: "for-sale",
    featured: true,
    agentId: "2",
    description:
      "Luxurious penthouse with city views and modern finishes. Located in the prestigious Piantini district, this penthouse offers floor-to-ceiling windows, high-end appliances, and a rooftop terrace perfect for entertaining.",
    amenities: ["Rooftop Pool", "Concierge", "Parking", "Gym", "24/7 Security"],
    createdAt: "2025-01-15",
  },
  {
    id: "3",
    title: "Tropical Garden Estate in Cabarete",
    price: 675000,
    location: "Cabarete, Puerto Plata",
    city: "Cabarete",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    ],
    bedrooms: 5,
    bathrooms: 5,
    area: 6000,
    type: "estate",
    status: "for-sale",
    featured: true,
    agentId: "3",
    description:
      "Sprawling tropical estate surrounded by lush gardens. This magnificent property features multiple entertaining spaces, a chef's kitchen, private pool, and guest quarters — ideal for large families or a boutique hotel venture.",
    amenities: ["Private Pool", "Garden", "Maid Quarters", "Garage", "BBQ Area"],
    createdAt: "2025-02-01",
  },
  {
    id: "4",
    title: "Beachside Apartment in Las Terrenas",
    price: 195000,
    location: "Las Terrenas, Samaná",
    city: "Las Terrenas",
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
    ],
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    type: "apartment",
    status: "for-sale",
    featured: false,
    agentId: "1",
    description:
      "Bright beachside apartment just minutes from the white sands of Las Terrenas. Modern open layout, fully equipped kitchen, and a breezy terrace with sea views.",
    amenities: ["Pool", "Beach Access", "Air Conditioning", "Parking"],
    createdAt: "2025-02-10",
  },
  {
    id: "5",
    title: "Golf Course Condo in Casa de Campo",
    price: 320000,
    location: "La Romana, La Romana",
    city: "La Romana",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
    ],
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    type: "condo",
    status: "for-sale",
    featured: false,
    agentId: "4",
    description:
      "Elegant condo overlooking the world-famous Teeth of the Dog golf course at Casa de Campo. Enjoy resort-style amenities, a private marina, and polo grounds.",
    amenities: ["Golf Access", "Pool", "Marina", "Security", "Concierge"],
    createdAt: "2025-02-20",
  },
  {
    id: "6",
    title: "Mountain View Villa in Jarabacoa",
    price: 280000,
    location: "Jarabacoa, La Vega",
    city: "Jarabacoa",
    images: [
      "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
    ],
    bedrooms: 4,
    bathrooms: 3,
    area: 3500,
    type: "villa",
    status: "for-sale",
    featured: false,
    agentId: "2",
    description:
      "Breathtaking villa nestled in the cool mountain air of Jarabacoa. Features a river-view terrace, fireplace, and lush tropical garden. Perfect for those seeking a tranquil escape from city life.",
    amenities: ["Garden", "Fireplace", "River View", "Parking", "BBQ Area"],
    createdAt: "2025-03-01",
  },
];

export const FEATURED_PROPERTIES: Property[] = ALL_PROPERTIES.filter((p) => p.featured);

export const AGENTS: Agent[] = [
  {
    id: "1",
    name: "Maria Rodriguez",
    title: "Luxury Property Specialist",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=200",
    listings: 47,
    sales: 32,
    rating: 4.9,
    phone: "+1 (809) 555-0101",
    email: "maria@expovivienda.com",
    bio: "Specialist in luxury beachfront properties with 10+ years experience.",
  },
  {
    id: "2",
    name: "Carlos Méndez",
    title: "Investment Property Expert",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
    listings: 38,
    sales: 44,
    rating: 4.8,
    phone: "+1 (809) 555-0102",
    email: "carlos@expovivienda.com",
    bio: "Expert in investment properties and commercial real estate.",
  },
  {
    id: "3",
    name: "Ana Martinez",
    title: "Coastal Properties Expert",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
    listings: 52,
    sales: 61,
    rating: 4.5,
    phone: "+1 (809) 555-0103",
    email: "ana@expovivienda.com",
    bio: "Coastal properties specialist focused on the North Coast.",
  },
  {
    id: "4",
    name: "Roberto Santos",
    title: "Premier Consultant",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
    listings: 43,
    sales: 38,
    rating: 4.8,
    phone: "+1 (809) 555-0104",
    email: "roberto@expovivienda.com",
    bio: "Helping families find their dream homes across the Dominican Republic.",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    userName: "Isabella Torres",
    userAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100",
    userLocation: "New York, USA",
    rating: 5,
    content:
      "ExpoVivienda made finding our beachfront villa incredibly easy. The virtual tour was amazing, and our agent Maria was exceptional throughout the entire process.",
  },
  {
    id: "2",
    userName: "Michael Anderson",
    userAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100",
    userLocation: "Toronto, Canada",
    rating: 5,
    content:
      "As an international investor, I appreciated the transparency and professionalism. The platform provided all the information needed to make confident investment decisions.",
  },
  {
    id: "3",
    userName: "Sofia Ramirez",
    userAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100",
    userLocation: "Miami, Florida",
    rating: 5,
    content:
      "The raffle program is brilliant! I won a consultation with a top agent and found my dream home. ExpoVivienda truly makes owning homeownership accessible.",
  },
];

export const VIRTUAL_EXPOS: VirtualExpo[] = [
  {
    id: "1",
    title: "Spring Property Fair 2025",
    description: "Explore hundreds of premium properties from the comfort of your home.",
    startDate: "2025-03-15",
    endDate: "2025-03-17",
    thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
    features: ["Live property tours", "Meet developers", "Interactive Q&A", "Exclusive deals"],
    status: "upcoming",
  },
];

export const RAFFLES: Raffle[] = [
  {
    id: "r1",
    propertyId: "1",
    property: ALL_PROPERTIES[0],
    ticketPrice: 25,
    totalTickets: 5000,
    soldTickets: 3241,
    endDate: "2026-05-30T00:00:00Z",
    status: "active",
  },
  {
    id: "r2",
    propertyId: "2",
    property: ALL_PROPERTIES[1],
    ticketPrice: 15,
    totalTickets: 3000,
    soldTickets: 1120,
    endDate: "2026-06-15T00:00:00Z",
    status: "active",
  },
];

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Properties", href: "/properties" },
  { label: "Virtual Expo", href: "/virtual-expo" },
  { label: "Raffles", href: "/raffles" },
  { label: "Agents", href: "/agents" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
