import { Property, Agent, Raffle, Testimonial, VirtualExpo } from "@/types";

export const FEATURED_PROPERTIES: Property[] = [
  {
    id: "1",
    title: "Luxury Beachfront Villa in Punta Cana",
    price: 850000,
    location: "Punta Cana, La Altagracia",
    city: "Punta Cana",
    images: ["/images/pro.jpg"],
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    type: "villa",
    status: "for-sale",
    featured: true,
    agentId: "1",
    description: "Stunning beachfront villa with panoramic ocean views.",
    amenities: ["Pool", "Beach Access", "Gym", "Security"],
    createdAt: "2025-01-01",
  },
  {
    id: "2",
    title: "Modern Penthouse in Santo Domingo",
    price: 425000,
    location: "Piantini, Santo Domingo",
    city: "Santo Domingo",
    images: ["/images/pro2.jpg"],
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    type: "penthouse",
    status: "for-sale",
    featured: true,
    agentId: "2",
    description: "Luxurious penthouse with city views and modern finishes.",
    amenities: ["Rooftop Pool", "Concierge", "Parking", "Gym"],
    createdAt: "2025-01-15",
  },
  {
    id: "3",
    title: "Tropical Garden Estate in Cabarete",
    price: 675000,
    location: "Cabarete, Puerto Plata",
    city: "Cabarete",
    images: ["/images/pro3.jpg"],
    bedrooms: 5,
    bathrooms: 5,
    area: 6000,
    type: "estate",
    status: "for-sale",
    featured: true,
    agentId: "3",
    description: "Sprawling tropical estate surrounded by lush gardens.",
    amenities: ["Private Pool", "Garden", "Maid Quarters", "Garage"],
    createdAt: "2025-02-01",
  },
  {
    id: "4",
    title: "Contemporary Condo in Las Terrenas",
    price: 295000,
    location: "Las Terrenas, Samaná",
    city: "Las Terrenas",
    images: ["/images/193c88179fac50bb382fa3e14501ac6f15ab0002.jpg"],
    bedrooms: 3,
    bathrooms: 2,
    area: 2400,
    type: "condo",
    status: "for-sale",
    featured: false,
    agentId: "4",
    description: "Bright coastal condo with ocean breezes and modern finishes.",
    amenities: ["Ocean View", "Pool", "Gym", "Parking"],
    createdAt: "2025-02-10",
  },
  {
    id: "5",
    title: "Oceanfront Townhome in Sosúa",
    price: 510000,
    location: "Sosúa, Puerto Plata",
    city: "Sosúa",
    images: ["/images/19bee260c61aab8ceae7e068c7cf4084d77c4f03.jpg"],
    bedrooms: 4,
    bathrooms: 3,
    area: 3600,
    type: "villa",
    status: "for-sale",
    featured: false,
    agentId: "1",
    description: "Elegant townhome steps from the beach with spacious interiors.",
    amenities: ["Beach Access", "Terrace", "Security", "Pool"],
    createdAt: "2025-02-18",
  },
  {
    id: "6",
    title: "Luxury Skyline Apartment in Santiago",
    price: 380000,
    location: "Santiago de los Caballeros",
    city: "Santiago",
    images: ["/images/41d1692bb4b354b2f931fd7e495ccbddf3273fab.jpg"],
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    type: "apartment",
    status: "for-sale",
    featured: false,
    agentId: "2",
    description: "High-floor apartment with skyline views and premium interiors.",
    amenities: ["City View", "Lobby", "Parking", "Gym"],
    createdAt: "2025-02-25",
  },
];

export const AGENTS: Agent[] = [
  {
    id: "1",
    name: "Maria Rodriguez",
    title: "Caribbean Realty Group",
    designation: "Senior Agent",
    avatar: "/images/me1.jpg",
    listings: 47,
    sales: 32,
    rating: 4.9,
    phone: "+1 (809) 555-0101",
    email: "maria@expovivienda.com",
    bio: "Specialist in luxury beachfront properties with 10+ years experience.",
  },
  {
    id: "2",
    name: "Carlos Méndez",
    title: "Tropical Properties DR",
    designation: "Luxury Specialist",
    avatar: "/images/me2.jpg",
    listings: 38,
    sales: 44,
    rating: 4.8,
    phone: "+1 (809) 555-0102",
    email: "carlos@expovivienda.com",
    bio: "Expert in investment properties and commercial real estate.",
  },
  {
    id: "3",
    name: "Ana Martinez",
    title: "Coastal Living Realty",
    designation: "Beachfront Expert",
    avatar: "/images/me1.jpg",
    listings: 52,
    sales: 61,
    rating: 4.5,
    phone: "+1 (809) 555-0103",
    email: "ana@expovivienda.com",
    bio: "Coastal properties specialist focused on the North Coast.",
  },
  {
    id: "4",
    name: "Roberto Santos",
    title: "Premier Estates DR",
    designation: "Investment Advisor",
    avatar: "/images/me2.jpg",
    listings: 43,
    sales: 38,
    rating: 4.8,
    phone: "+1 (809) 555-0104",
    email: "roberto@expovivienda.com",
    bio: "Helping families find their dream homes across the Dominican Republic.",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    userName: "Isabella Torres",
    userAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100",
    userLocation: "New York, USA",
    rating: 5,
    content:
      "ExpoVivienda made finding our beachfront villa incredibly easy. The virtual tour was amazing, and our agent Maria was exceptional throughout the entire process.",
  },
  {
    id: "2",
    userName: "Michael Anderson",
    userAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100",
    userLocation: "Toronto, Canada",
    rating: 5,
    content:
      "As an international investor, I appreciated the transparency and professionalism. The platform provided all the information needed to make confident investment decisions.",
  },
  {
    id: "3",
    userName: "Sofia Ramirez",
    userAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100",
    userLocation: "Miami, Florida",
    rating: 5,
    content:
      "The raffle program is brilliant! I won a consultation with a top agent and found my dream home. ExpoVivienda truly makes owning homeownership accessible.",
  },
  {
    id: "4",
    userName: "Sofia Ramirez",
    userAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100",
    userLocation: "Miami, Florida",
    rating: 5,
    content:
      "The raffle program is brilliant! I won a consultation with a top agent and found my dream home. ExpoVivienda truly makes owning homeownership accessible.",
  },
  {
    id: "5",
    userName: "Sofia Ramirez",
    userAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100",
    userLocation: "Miami, Florida",
    rating: 5,
    content:
      "The raffle program is brilliant! I won a consultation with a top agent and found my dream home. ExpoVivienda truly makes owning homeownership accessible.",
  },
  {
    id: "6",
    userName: "Sofia Ramirez",
    userAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100",
    userLocation: "Miami, Florida",
    rating: 5,
    content:
      "The raffle program is brilliant! I won a consultation with a top agent and found my dream home. ExpoVivienda truly makes owning homeownership accessible.",
  },
];

export const VIRTUAL_EXPOS: VirtualExpo[] = [
  {
    id: "1",
    title: "Spring Property Fair 2025",
    description: "Explore hundreds of premium properties from the comfort of your home.",
    startDate: "2025-03-15",
    endDate: "2025-03-17",
    thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
    features: ["Live property tours", "Meet developers", "Interactive Q&A", "Exclusive deals"],
    status: "upcoming",
  },
];

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Properties", href: "/properties" },
  // { label: "Property Fair", href: "/property-fair" },
  { label: "Raffles", href: "/raffle" },
  { label: "Agents", href: "/agentss" },
  { label: "About", href: "/about-page" },
  { label: "Contact", href: "/contact" },
];
